# Reference: http://mkdocs.org
site_name: <<Enter the title here>>
site_author: <<Enter your name>>
pages:
  - 'Introduction': index.md
  - 'Introduction':
    - 'A sample slideshow': slides/intro.md
extra:
  mailto: <<Enter your email address here>>
# Plugins available at: http://bwmarrin.github.io/MkDocsPlus/datatables/
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - codehilite
  - fenced_code
  - fontawesome_markdown
  - nl2br
  - tables
extra_javascript: []
extra_css: []
# if true: use e.g. '/subdir/' instead of '/subdir/index.html'
use_directory_urls: true
theme: readthedocs
docs_dir: src
theme_dir: theme
build_dir: '/tmp'
#dev_addr: '0.0.0.0:8000'
